services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - '5433:5432'
    build:
      context: .
      dockerfile: Dockerfile.db
      target: motorway-postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=motorway
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    environment:
      - REDIS_PASSWORD=password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
  vehicles-api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vehicles-api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://user:password@postgres:5432/motorway?schema=public
      - REDIS_CACHE_TTL=60
      - POSTGRES_PASSWORD=password
    ports:
      - '3000:3000'
    volumes:
      - ../src:/app/src
volumes:
  cache:
    driver: local